### ISSUE TITLE
Can you provide spot_comp8.data

### ISSUE THREAD

**Issue by liuxiao916** [roahmlab/sel_map#3]
Hi,

Thank you for your great work. Can you provide the rosbag to help me test it?

`rosbag play spot_comp8.data --clock --pause`

**Comment by BuildingAtom** [comment]
Sure thing! [Here's a link to spot_comp8.bag](https://drive.google.com/file/d/16KGBpe8B3ZpDN-ryfNTRw_Ratqv6kCKg/view?usp=sharing), also for anyone else who might want to try with that same bag. This bag wasn't included in the figures for the final published paper, [here is a link to spot_comp3.bag](https://drive.google.com/file/d/1ujXyCtcNUrqXXau7gifMc1TalFNUtfOX/view?usp=sharing) which corresponds to figure 5b in our paper.

We generated the figure with the default `semseg=CSAIL_ResNet50ppm_ADE_full.yaml`, but for realtime performance, we recommend `semseg=Encoding_ResNet50_ADE_onehot.yaml`.

Please let us know if you have any issues! If not, I'll go ahead and close this issue.

**Comment by liuxiao916** [comment]
Cool! Thanks.

**Comment by liuxiao916** [comment]
By the way, when I want to test rosbag. I should launch `spot_bag_sel.launch` instead of `spot_sel.launch`. I spent a lot of to debug why `image_transport` didn't work.
