### ISSUE TITLE
Incorrect transform between camera and robot

### ISSUE THREAD

**Issue by Daisy-GENG** [roahmlab/sel_map#6]
Hi, thanks for your excellen work! When I was running your code and the spot_comp3.bag, the transform between the camera and the robot seems to be incorrect. Because the map is inclined to the robot shown in the rviz, but the real word seems to be horizontal according to the rgb image. And I tried every sequence of the parameters offered in the spot_bag.yaml / spot.yaml (transform between camera_link and front_rail), but the visualization results are all the same.

![image](https://user-images.githubusercontent.com/52648643/228743866-c6062fd2-e000-407e-8756-fc83c7248916.png)

I was wondering if the transform between the camera and robot is hardcoded in the code, as is done in line 82 of main.py in the main branch?

https://github.com/roahmlab/sel_map/blob/caea37f61b91f49e84959a8891e933cd7f275146/sel_map/scripts/main.py#L76

**Comment by BuildingAtom** [comment]
Hi @Daisy-GENG, do you mind sharing more information? What command do you
use for roslaunch? What robot configuration are you using?

All the initial information in the repository should work with that bag.
The `R` matrix is there to swap axis depending on how the camera frame's
transform or pose is defined. It shouldn't need to change. For the main
transform, the node should be obtaining the transform to the camera as the
`pose` variable using data from TF2, and it should be obtaining `intrinsic`
from the relevant camera_info topic.

**Comment by Daisy-GENG** [comment]
Hi, thank you so much for your answer! It turned out that I additionaly added the rostopic name for pose in the spot_bag.yaml. And after changing the "publish_rate" and "queue_size" in the launch file, the map update frequency in rviz tends to be larger, and the incompleteness of the map shown in rviz has also been resolved.

Thanks again!

Daisy

**Comment by BuildingAtom** [comment]
Hi Daisy, glad to hear that you got it working! I'll go ahead and mark this issue as closed too. If you have any other issues, feel free to open another issue or leave another comment
